# Generated by Django 5.2.12 on 2026-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_last_login_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='days_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_minutes_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
