# Generated by Django 5.2.12 on 2026-03-10 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('topic_title', models.CharField(max_length=255)),
                ('explained', models.BooleanField(default=False)),
                ('chatted', models.BooleanField(default=False)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'topic_title'],
                'unique_together': {('user', 'category', 'topic_title')},
            },
        ),
    ]
